# Generated by Django 4.1.7 on 2023-02-25 11:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('minitwit', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
